name:        project
version:     0.1.0
synopsis:    Project
description: Project
maintainer:  Adjoint Inc (info@adjoint.io)
license:     BSD3
github:      adjoint-io/project
category:    Cryptography

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - NoImplicitPrelude

dependencies:
  - base           >= 4.10  && < 5
  - protolude      >= 0.2   && < 0.3

extra-source-files:
  - README.md
  - ChangeLog.md

ghc-options:
  - -freverse-errors
  - -Wall

library:
  exposed-modules:
    - Lib
  source-dirs:
    - src

executables:
  project-exe:
    main: Main
    source-dirs:
      - exe
    dependencies:
      - project

tests:
  project-tests:
    main: Main
    dependencies:
      - project
      - tasty                   >= 1.2  && <1.3
      - tasty-discover          >= 4.2  && <4.3
      - tasty-hunit             >= 0.10 && <0.11
      - tasty-quickcheck        >= 0.10 && <0.11
      - QuickCheck              >= 2.12 && <2.14
      - quickcheck-instances    >= 0.3  && <0.4
    source-dirs:
      - test
